/**
 * The Telegram bot's daily word (api/_lib/studentBot.ts): words and phrases
 * that raise an IELTS Writing band. For each one, a student gets the Uzbek
 * meaning, a short precise English definition, a note on how it functions in
 * a sentence (part of speech, what it takes before/after it), and an example
 * in the kind of sentence a Task 1 or Task 2 answer needs. Chosen only for
 * Writing: no reading- or listening-only vocabulary. Each student moves
 * through the list in order, so nobody gets a repeat until they have had
 * every word.
 */
export interface DailyWord {
  word: string;
  uzbek: string;
  /** Short, precise English definition - what the word actually means. */
  meaning: string;
  /** How it functions in a sentence: part of speech, and what it takes before/after it. */
  usage: string;
  example: string;
}

export const DAILY_WORDS: DailyWord[] = [
  {
    word: "significant",
    uzbek: "sezilarli, muhim",
    meaning: "large or important enough to be noticed",
    usage: "adjective, before a noun or after 'be' (a significant rise / the rise was significant)",
    example:
      "There was a significant rise in car ownership between 2000 and 2020.",
  },
  {
    word: "decline",
    uzbek: "kamaymoq, pasaymoq",
    meaning: "to become smaller, weaker or lower",
    usage: "verb, often with an adverb of speed (declined sharply/gradually)",
    example: "The number of visitors declined sharply after 2015.",
  },
  {
    word: "fluctuate",
    uzbek: "o'zgarib turmoq",
    meaning: "to keep changing up and down, with no steady pattern",
    usage: "verb, describes unstable data over time (prices fluctuated)",
    example: "Oil prices fluctuated throughout the year.",
  },
  {
    word: "approximately",
    uzbek: "taxminan",
    meaning: "close to a number, but not exact",
    usage: "adverb, directly before a number (approximately 30%)",
    example: "Approximately a third of students live on campus.",
  },
  {
    word: "account for",
    uzbek: "(ulushini) tashkil qilmoq",
    meaning: "to make up a stated share or amount of a total",
    usage: "phrasal verb + a percentage or proportion (cars account for 60%)",
    example: "Cars account for 60% of all journeys to work.",
  },
  {
    word: "consequently",
    uzbek: "natijada, shuning uchun",
    meaning: "as a direct result of what was just said",
    usage: "linking adverb, starts a sentence + comma, joins a cause to its effect",
    example:
      "Rents rose quickly; consequently, many families moved to the suburbs.",
  },
  {
    word: "alleviate",
    uzbek: "yengillashtirmoq",
    meaning: "to make a problem less severe",
    usage: "verb + a problem noun (alleviate congestion/poverty)",
    example: "Better public transport can alleviate traffic congestion.",
  },
  {
    word: "detrimental",
    uzbek: "zararli",
    meaning: "causing harm or damage",
    usage: "adjective + 'to' (detrimental to health)",
    example: "Too much screen time is detrimental to children's sleep.",
  },
  {
    word: "beneficial",
    uzbek: "foydali",
    meaning: "having a good or helpful effect",
    usage: "adjective + 'for/to' (beneficial for mental health)",
    example: "Regular exercise is beneficial for mental health.",
  },
  {
    word: "inevitable",
    uzbek: "muqarrar",
    meaning: "certain to happen; impossible to avoid",
    usage: "adjective, usually after 'be' (job losses are inevitable)",
    example: "Some job losses are inevitable as technology develops.",
  },
  {
    word: "undermine",
    uzbek: "putur yetkazmoq",
    meaning: "to gradually make something weaker",
    usage: "verb + an abstract noun (undermine trust/confidence)",
    example: "Cheating undermines trust in exam results.",
  },
  {
    word: "prioritise",
    uzbek: "birinchi o'ringa qo'ymoq",
    meaning: "to treat one thing as more important than others",
    usage: "verb + noun, often with 'over' (prioritise health over wealth)",
    example: "Governments should prioritise public health over road building.",
  },
  {
    word: "sustainable",
    uzbek: "barqaror",
    meaning: "able to continue long-term without using up resources or causing harm",
    usage: "adjective before a noun (sustainable energy/development)",
    example: "Cities need sustainable ways to produce energy.",
  },
  {
    word: "deteriorate",
    uzbek: "yomonlashmoq",
    meaning: "to become worse",
    usage: "verb, no object (conditions/air quality deteriorated)",
    example: "Air quality has deteriorated in many large cities.",
  },
  {
    word: "enhance",
    uzbek: "yaxshilamoq, oshirmoq",
    meaning: "to improve the quality or value of something",
    usage: "verb + noun (enhance skills/vocabulary/performance)",
    example: "Reading widely can enhance a student's vocabulary.",
  },
  {
    word: "widespread",
    uzbek: "keng tarqalgan",
    meaning: "existing or happening over a large area or among many people",
    usage: "adjective before a noun (widespread use/concern)",
    example: "Mobile banking is now widespread in Uzbekistan.",
  },
  {
    word: "contribute to",
    uzbek: "sabab bo'lmoq, hissa qo'shmoq",
    meaning: "to be one of the things that helps cause a result",
    usage: "phrasal verb + noun (contribute to obesity/success)",
    example: "Fast food contributes to rising obesity.",
  },
  {
    word: "a growing number of",
    uzbek: "tobora ko'payib borayotgan",
    meaning: "an amount that keeps increasing",
    usage: "quantifier phrase + plural noun (a growing number of students)",
    example: "A growing number of students study online.",
  },
  {
    word: "stem from",
    uzbek: "kelib chiqmoq",
    meaning: "to originate from, to be caused by",
    usage: "phrasal verb + noun (problems stem from poverty)",
    example: "Many health problems stem from a poor diet.",
  },
  {
    word: "essential",
    uzbek: "zarur, juda muhim",
    meaning: "absolutely necessary",
    usage: "adjective + 'for' (essential for survival)",
    example: "Clean water is essential for every community.",
  },
  {
    word: "peak",
    uzbek: "eng yuqori nuqtaga yetmoq",
    meaning: "to reach the highest point",
    usage: "verb (sales peaked) or noun after 'at its' (at its peak)",
    example: "Sales peaked in December at 5,000 units.",
  },
  {
    word: "level off",
    uzbek: "barqarorlashmoq",
    meaning: "to stop rising or falling and stay at the same level",
    usage: "phrasal verb, used after describing a rise or fall (rose, then levelled off)",
    example: "Unemployment levelled off after 2018.",
  },
  {
    word: "surge",
    uzbek: "keskin o'sish",
    meaning: "a sudden, large increase",
    usage: "noun + 'in' (a surge in demand) or verb (demand surged)",
    example: "There was a surge in online shopping in 2020.",
  },
  {
    word: "marginal",
    uzbek: "juda kichik, sezilmas",
    meaning: "very small in size or effect",
    usage: "adjective before 'increase/change/difference'",
    example: "There was only a marginal increase in bus fares.",
  },
  {
    word: "the overwhelming majority",
    uzbek: "mutlaq ko'pchilik",
    meaning: "almost all of a group",
    usage: "noun phrase + 'of' + plural noun",
    example: "The overwhelming majority of teenagers own a smartphone.",
  },
  {
    word: "place a burden on",
    uzbek: "og'irlik solmoq",
    meaning: "to create a heavy responsibility or cost for someone",
    usage: "verb phrase + noun (places a burden on hospitals)",
    example: "An ageing population places a burden on hospitals.",
  },
  {
    word: "tackle",
    uzbek: "hal qilishga kirishmoq",
    meaning: "to deal directly with a difficult problem",
    usage: "verb + a problem noun (tackle unemployment/crime)",
    example: "Governments must tackle unemployment among young people.",
  },
  {
    word: "affordable",
    uzbek: "hamyonbop",
    meaning: "priced low enough for people to reasonably pay",
    usage: "adjective before a noun (affordable housing)",
    example: "Housing should be affordable for young families.",
  },
  {
    word: "reluctant",
    uzbek: "istamaydigan, ikkilanadigan",
    meaning: "unwilling to do something",
    usage: "adjective + 'to' + verb (reluctant to change)",
    example: "Many people are reluctant to change their eating habits.",
  },
  {
    word: "compulsory",
    uzbek: "majburiy",
    meaning: "required by a law or rule, not optional",
    usage: "adjective, often after 'be' (be compulsory for students)",
    example:
      "Some people think voluntary work should be compulsory for students.",
  },
  {
    word: "hinder",
    uzbek: "to'sqinlik qilmoq",
    meaning: "to make progress or action more difficult",
    usage: "verb + noun (hinders learning/development)",
    example: "Slow internet access hinders online learning in villages.",
  },
  {
    word: "in the long run",
    uzbek: "uzoq muddatda",
    meaning: "over a long period of time in the future",
    usage: "fixed phrase, usually starts a sentence + comma",
    example: "In the long run, a good education pays for itself.",
  },
  {
    word: "drawback",
    uzbek: "kamchilik",
    meaning: "a disadvantage of a plan or situation",
    usage: "noun, often 'the main drawback of...'",
    example: "The main drawback of city life is the noise.",
  },
  {
    word: "advocate",
    uzbek: "yoqlab chiqmoq",
    meaning: "to publicly support or recommend an idea",
    usage: "verb + noun, no preposition (advocate a shorter working week)",
    example: "Some doctors advocate a shorter working week.",
  },
  {
    word: "pursue",
    uzbek: "intilmoq, davom ettirmoq",
    meaning: "to keep working towards a goal over time",
    usage: "verb + noun (pursue a career/goal)",
    example: "More women now pursue careers in science.",
  },
  {
    word: "vulnerable",
    uzbek: "himoyasiz, zaif",
    meaning: "easily harmed physically or emotionally",
    usage: "adjective, often + 'to' (vulnerable to disease/poverty)",
    example: "Elderly people are especially vulnerable in hot weather.",
  },
  {
    word: "adverse",
    uzbek: "salbiy",
    meaning: "unfavourable or harmful",
    usage: "adjective before 'effect(s)/impact' (adverse effects)",
    example: "The new tax had adverse effects on small businesses.",
  },
  {
    word: "mitigate",
    uzbek: "kamaytirmoq, yumshatmoq",
    meaning: "to make something bad less severe",
    usage: "verb + a problem noun (mitigate the risk/heat)",
    example: "Planting trees can mitigate the heat in cities.",
  },
  {
    word: "commute",
    uzbek: "ishga qatnamoq",
    meaning: "to travel regularly between home and work",
    usage: "verb (commute to work) or noun (a long commute)",
    example: "Many workers commute for more than an hour a day.",
  },
  {
    word: "urbanisation",
    uzbek: "shaharlashuv",
    meaning: "the process of more people moving into cities",
    usage: "noun, often the subject (rapid urbanisation)",
    example: "Rapid urbanisation puts pressure on housing.",
  },
  {
    word: "an ageing population",
    uzbek: "qariyotgan aholi",
    meaning: "a population in which the share of older people is rising",
    usage: "noun phrase, often the subject of a sentence",
    example: "Japan has an ageing population and a shrinking workforce.",
  },
  {
    word: "proportion",
    uzbek: "ulush, nisbat",
    meaning: "a part or share of a whole, often as a percentage",
    usage: "noun + 'of' (the proportion of people over 65)",
    example: "The proportion of people over 65 increased steadily.",
  },
  {
    word: "respectively",
    uzbek: "mos ravishda",
    meaning: "in the same order as the items already mentioned",
    usage: "adverb at the end of a sentence, after a list of figures",
    example: "Sales reached 20% and 35% in 2000 and 2010 respectively.",
  },
  {
    word: "whereas",
    uzbek: "holbuki, ... esa",
    meaning: "used to compare two different or opposite facts",
    usage: "linking word joining two clauses, comma before the second clause",
    example: "Men spent more on cars, whereas women spent more on clothes.",
  },
  {
    word: "subsequently",
    uzbek: "keyinchalik",
    meaning: "afterwards, at a later time",
    usage: "adverb, often at the start of a clause",
    example: "Prices rose in 2008 and subsequently fell.",
  },
  {
    word: "remain stable",
    uzbek: "o'zgarmay qolmoq",
    meaning: "to stay at about the same level, with no big change",
    usage: "verb phrase describing a flat trend, + 'at' a figure",
    example: "Coffee sales remained stable at around 200 tonnes.",
  },
  {
    word: "to a large extent",
    uzbek: "katta darajada",
    meaning: "mostly true, but not completely",
    usage: "fixed phrase for partly agreeing (I agree to a large extent)",
    example: "I agree with this view to a large extent.",
  },
  {
    word: "raise awareness of",
    uzbek: "xabardorlikni oshirmoq",
    meaning: "to make more people know about an issue",
    usage: "verb phrase + noun (raise awareness of healthy eating)",
    example: "Campaigns can raise awareness of healthy eating.",
  },
  {
    word: "take into account",
    uzbek: "hisobga olmoq",
    meaning: "to consider something when deciding or judging",
    usage: "verb phrase + noun (take into account the needs of...)",
    example: "Planners must take into account the needs of older people.",
  },
  {
    word: "outweigh",
    uzbek: "ustun bo'lmoq",
    meaning: "to be greater or more important than something else",
    usage: "verb + noun, no preposition (benefits outweigh drawbacks)",
    example: "In my view, the benefits of tourism outweigh its drawbacks.",
  },
  {
    word: "namely",
    uzbek: "aynan, ya'ni",
    meaning: "used just before naming exactly what you mean",
    usage: "adverb before a list of specific examples",
    example: "Two factors explain this, namely cost and convenience.",
  },
  {
    word: "notably",
    uzbek: "ayniqsa, xususan",
    meaning: "used to draw attention to one especially important example",
    usage: "adverb, often mid-sentence between commas",
    example: "Several cities, notably London, have banned diesel cars.",
  },
  {
    word: "conversely",
    uzbek: "aksincha",
    meaning: "in a way that is the opposite of what was just said",
    usage: "linking adverb, starts a sentence + comma",
    example: "Rural areas have cheap housing; conversely, city housing is expensive.",
  },
  {
    word: "give rise to",
    uzbek: "sabab bo'lmoq, keltirib chiqarmoq",
    meaning: "to cause something, usually a problem, to happen",
    usage: "verb phrase + noun (gives rise to problems)",
    example: "Rapid growth has given rise to serious traffic problems.",
  },
  {
    word: "it could be argued that",
    uzbek: "shunday deb aytish mumkinki",
    meaning: "used to introduce a debatable opinion in a careful, formal way",
    usage: "fixed opener for an opinion sentence, + full clause",
    example: "It could be argued that online learning suits fewer students.",
  },
  {
    word: "this is largely due to",
    uzbek: "bu asosan ... sababli",
    meaning: "used to give the main cause of something just described",
    usage: "fixed phrase, followed by a noun phrase",
    example: "This is largely due to the rise in remote working.",
  },
  {
    word: "far outweigh",
    uzbek: "ancha ustun bo'lmoq",
    meaning: "to be much greater or more important than something else",
    usage: "verb + noun, a stronger version of 'outweigh'",
    example: "The benefits of exercise far outweigh the risks.",
  },
  {
    word: "constitute",
    uzbek: "tashkil qilmoq",
    meaning: "to form or make up a whole",
    usage: "verb + noun, a formal alternative to 'make up' (constitutes a quarter)",
    example: "Young people constitute a quarter of the city's population.",
  },
  {
    word: "the vast majority of",
    uzbek: "aksariyat qismi",
    meaning: "almost all of something",
    usage: "quantifier phrase + 'of' + plural noun",
    example: "The vast majority of households now own a computer.",
  },
  {
    word: "plummet",
    uzbek: "keskin tushib ketmoq",
    meaning: "to fall suddenly and very quickly",
    usage: "verb, a stronger version of 'decline/fall'",
    example: "Share prices plummeted after the announcement.",
  },
  {
    word: "soar",
    uzbek: "keskin ko'tarilmoq",
    meaning: "to rise very quickly to a high level",
    usage: "verb, a stronger version of 'rise/increase'",
    example: "Demand for electric cars soared last year.",
  },
  {
    word: "steady growth",
    uzbek: "barqaror o'sish",
    meaning: "an increase that happens at a regular, even rate",
    usage: "noun phrase describing a smooth rising line on a graph",
    example: "The graph shows steady growth in exports since 2015.",
  },
  {
    word: "a sharp contrast",
    uzbek: "keskin farq",
    meaning: "a very clear and strong difference",
    usage: "noun phrase, often + 'in/between'",
    example: "There is a sharp contrast between rural and urban incomes.",
  },
  {
    word: "on the other hand",
    uzbek: "boshqa tomondan",
    meaning: "used to introduce an opposite or different point",
    usage: "fixed phrase, starts a sentence + comma",
    example: "On the other hand, working from home can feel isolating.",
  },
  {
    word: "in contrast to",
    uzbek: "-ga qaraganda, farqli o'laroq",
    meaning: "when compared with something different",
    usage: "preposition phrase + noun (in contrast to 2010)",
    example: "In contrast to 2010, car ownership has doubled.",
  },
  {
    word: "it should be borne in mind that",
    uzbek: "shuni yodda tutish kerakki",
    meaning: "used to ask the reader to remember an important point",
    usage: "fixed formal opener + full clause",
    example: "It should be borne in mind that not everyone has internet access.",
  },
  {
    word: "a case in point is",
    uzbek: "buning yaqqol misoli",
    meaning: "used to introduce a clear, specific example of what was just said",
    usage: "fixed phrase before naming an example",
    example: "A case in point is the rise of online shopping during the pandemic.",
  },
  {
    word: "arguably",
    uzbek: "aytish mumkinki, ehtimol",
    meaning: "probably true, based on the evidence available",
    usage: "adverb before an adjective or claim (arguably the best solution)",
    example: "This is arguably the most effective solution to the problem.",
  },
  {
    word: "in a similar vein",
    uzbek: "shunga o'xshash tarzda",
    meaning: "in a way that is similar to what was just said",
    usage: "fixed phrase to introduce a similar point, starts a sentence",
    example: "In a similar vein, public transport has also become more expensive.",
  },
  {
    word: "to compound the problem",
    uzbek: "muammoni yanada kuchaytirish uchun",
    meaning: "used when something makes an existing problem even worse",
    usage: "fixed phrase, often opens a new sentence",
    example: "To compound the problem, fuel prices rose at the same time.",
  },
  {
    word: "a plausible explanation is",
    uzbek: "ishonarli tushuntirish",
    meaning: "a reasonable and believable reason for something",
    usage: "fixed phrase before stating a cause",
    example: "A plausible explanation is the growth of remote working.",
  },
  {
    word: "counterproductive",
    uzbek: "teskari natija beruvchi",
    meaning: "having the opposite effect to the one that was intended",
    usage: "adjective, usually after 'be' (would be counterproductive)",
    example: "Banning cars overnight would be counterproductive.",
  },
  {
    word: "a viable solution",
    uzbek: "amalga oshirish mumkin bo'lgan yechim",
    meaning: "a solution that is realistic and likely to actually work",
    usage: "noun phrase, often the object (offers a viable solution)",
    example: "Public transport offers a viable solution to congestion.",
  },
  {
    word: "in summary",
    uzbek: "xulosa qilib aytganda",
    meaning: "used to introduce the final summary of an essay",
    usage: "fixed opener for a conclusion paragraph, + comma",
    example: "In summary, the benefits of remote work outweigh the drawbacks.",
  },
  {
    word: "all things considered",
    uzbek: "hammasini hisobga olganda",
    meaning: "after thinking about every relevant point",
    usage: "fixed phrase, often opens the final, concluding sentence",
    example: "All things considered, stricter laws seem the best approach.",
  },
];
